services:
  db:
    image: postgres
    restart: always
    ports:
      - 8877:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: kiruha
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  adminer:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: kiruha@kiruha.ru
      PGADMIN_DEFAULT_PASSWORD: kiruha

volumes:
  dbdata:
