services:
  db:
    image: postgres
    restart: always
    ports:
      - 8877:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: kiruha
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  mysql:
    image: mysql
    restart: always
    ports:
      - 8899:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example
      MYSQL_USER: kiruha
      MYSQL_DATABASE: kiruha
    volumes:
      - "mysql_data:/var/lib/mysql"


  mysql_test:
    image: mysql
    restart: always
    ports:
      - 8900:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example
      MYSQL_USER: kiruha
      MYSQL_DATABASE: testuha
    volumes:
      - "mysql_test_data:/var/lib/mysql"


  adminer:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: kiruha@kiruha.ru
      PGADMIN_DEFAULT_PASSWORD: kiruha

volumes:
  dbdata:
